### ISSUE TITLE
fail to load macosx backend

### ISSUE THREAD

**Issue by jschueller** [conda-forge/matplotlib-feedstock#91]
hi,
I suspect there's a problem since #87 as my recipes involving matplotlib fail now on travis:
```
import matplotlib.pyplot as plt

  File "/Users/travis/miniconda3/conda-bld/recipe_1483084010906/_t_env/lib/python2.7/site-packages/matplotlib/pyplot.py", line 114, in <module>

    _backend_mod, new_figure_manager, draw_if_interactive, _show = pylab_setup()

  File "/Users/travis/miniconda3/conda-bld/recipe_1483084010906/_t_env/lib/python2.7/site-packages/matplotlib/backends/__init__.py", line 32, in pylab_setup

    globals(),locals(),[backend_name],0)

  File "/Users/travis/miniconda3/conda-bld/recipe_1483084010906/_t_env/lib/python2.7/site-packages/matplotlib/backends/backend_macosx.py", line 24, in <module>

    from matplotlib.backends import _macosx

RuntimeError: Python is not installed as a framework. The Mac OS X backend will not be able to function correctly if Python is not installed as a framework. See the Python documentation for more information on installing Python as a framework on Mac OS X. Please either reinstall Python as a framework, or try one of the other backends. If you are Working with Matplotlib in a virtual enviroment see 'Working with Matplotlib in Virtual environments' in the Matplotlib FAQ
```

failing builds:
https://github.com/conda-forge/openturns-feedstock/pull/24
https://github.com/conda-forge/pyagrum-feedstock/pull/9

**Comment by amelio-vazquez-reina** [comment]
I am having the same problem here. Also reported it here: https://github.com/matplotlib/matplotlib/issues/7709

**Comment by amelio-vazquez-reina** [comment]
@jschueller any suggestions on how to downgrade to the previous version in `conda-forge`?

**Comment by dopplershift** [comment]
We recently re-enabled the osx backend, since it builds now on our infrastructure. #92 should fix the problem, as it applies the same patch from defaults that deals with matplotlib's check for a framework version of Python. Workarounds:

1. Run with `pythonw` rather than `python`
2. Set a different backend for matplotlib in `matplotlibrc`
3. Pass another backend on the command line, e.g. `-dQt4Agg`
4. Set the `MPLBACKEND` environment variable (to e.g. `Qt4Agg`)

**Comment by dopplershift** [comment]
Should be fixed by #92. Feel free to re-open if that's not the case.

**Comment by jschueller** [comment]
it's still failling as 2.0.0rc2-np111py27_1 gets pulled: the fix must be included in the devel branch too

**Comment by ocefpaf** [comment]
> it's still failling as 2.0.0rc2-np111py27_1 gets pulled: the fix must be included in the devel branch too:
https://travis-ci.org/conda-forge/pyagrum-feedstock/jobs/187877081
please reopen

See https://github.com/conda-forge/matplotlib-feedstock/pull/93

**Comment by jschueller** [comment]
any idea why the previous build (2.0.0rc2-np111py34_1) does still get picked up over 2.0.0rc2-np111py34_2 on osx-64 ?
https://travis-ci.org/conda-forge/pyagrum-feedstock/jobs/188192595
https://anaconda.org/conda-forge/matplotlib/files lists osx-64/matplotlib-2.0.0rc2-np111py34_2.tar.bz2

**Comment by dopplershift** [comment]
Any chance restarting the job now just magically fixes it?

**Comment by dopplershift** [comment]
2.0rc2 package is incorrectly on the main label on the conda-forge channel. I've asked to have it re-labelled, which should fix it.

**Comment by ocefpaf** [comment]
> 2.0rc2 package is incorrectly on the main label on the conda-forge channel. I've asked to have it re-labelled, which should fix it.

Done!
